### ISSUE TITLE
Issue with deleting a specific breakpoints 

### ISSUE THREAD

**Issue by dragonble** [cyrus-and/gdb#4]
Hi, I try to delete  a specific breakpoint but no matter how many I try I can't delete that breakpoint:

```
                    var numero_break string     

                    fmt.Println("delete one breakpoint  (n°) ")
                    fmt.Scanln(&numero_break )


                    fmt.Println(debug.Send("break-delete",numero_break)
```

maybe I did an error somewhere?
and My other issue is  to expose the variables list of a specific frame in my stack:

debug.Send("stack-list-variables","--thread","1", "--frame",string(i), "--simple-values")

I have this error :   map[class:error payload:map[msg:-stack-list-variables: Unknown option ``-thread'']] <nil>

But the same command(remplacing sting(i) by a number of a frame) with GDB/MI give me the right answer
"-stack-list-variables --thread 1 --frame 1 --simple-values"   give me the list of variables in the second frame

Thanks.

**Comment by cyrus-and** [comment]
It should work now; give it a try and let me know.
Thanks for reporting.

**Comment by dragonble** [comment]
you are right , my two issues have been fixed now

Thanks .
